### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by XS3209** [AlopexTMNT/AlopexBot#5]
There is a memory leak when the bot starts. Sometimes it crashes the bot

**Comment by AlopexTMNT** [comment]
The Crashing problem should be fixed. Looking into the memory leak problem.

**Comment by AlopexFeet** [comment]
I've got the same issue

**Comment by AlopexTMNT** [comment]
As long as it doesn't impact the bot's performance and doesn't crash it's fine. But still thanks!
